{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.3/core-2.3.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "core",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-mingwX64Main.klib",
          "url": "core-mingwx64-2.3.klib",
          "size": 15399,
          "sha512": "5a91ed66a25aa2ff46a98c4a56a4e020afa37d4991a0719da59174a735d92f90dad20a6e869357cb5da2309a9a3ddab3f5e01a6b6e1597f1d1625534cb237932",
          "sha256": "a45b2055f3c8412d257b44943f411fe71a760281fe042495b16e0603d1855e7d",
          "sha1": "9a2381cab58639aa489090fff47aca799d221f11",
          "md5": "1ac1451ad1d51d5fe6e545da0b8b8c5a"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-mingwx64-sources.jar",
          "url": "core-mingwx64-2.3-sources.jar",
          "size": 2206,
          "sha512": "0c4753353c410582be4a34befa30e4d938c2ca66b3697d9e95e1c3256b990d9c4356420bcbd79f829b7eb9820c45fb71df2f1d03bba89c9441befd6f36dba188",
          "sha256": "a6f1f4ee6f21e37eb661688d5298919607b559fd8786fed2c97398bc6260b30f",
          "sha1": "22e31f75259a147be8e4333b28f51c6d9cfceea0",
          "md5": "391c407b1f251c031ca81f94c6c4d910"
        }
      ]
    }
  ]
}
