{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose/2.2607.5/compose-2.2607.5.module",
    "group": "ren.shiror.fyl.fytxt",
    "module": "compose",
    "version": "2.2607.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "compose-jvm.jar",
          "url": "compose-jvm-2.2607.5.jar",
          "size": 10551,
          "sha512": "9fa49352aaaa9f58f7fbdee81f3d6fcae73240d01d10732ae1ada2012116760739543d187e9bd7d71be3b0fae8ed025a69de3489757f0a41baacb286e8ca0481",
          "sha256": "023ab2efa09a8760af76c9cf44bde7584f67f89bd910a91b5633d016c95adc25",
          "sha1": "e4fd490a2aab1ad8a753c321cac3601d9cff9675",
          "md5": "0402fe56f41cd302e3d8635783a4d259"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "ren.shiror.fyl.fytxt",
          "module": "core",
          "version": {
            "requires": "2.2607.5"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "compose-jvm.jar",
          "url": "compose-jvm-2.2607.5.jar",
          "size": 10551,
          "sha512": "9fa49352aaaa9f58f7fbdee81f3d6fcae73240d01d10732ae1ada2012116760739543d187e9bd7d71be3b0fae8ed025a69de3489757f0a41baacb286e8ca0481",
          "sha256": "023ab2efa09a8760af76c9cf44bde7584f67f89bd910a91b5633d016c95adc25",
          "sha1": "e4fd490a2aab1ad8a753c321cac3601d9cff9675",
          "md5": "0402fe56f41cd302e3d8635783a4d259"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "compose-jvm-sources.jar",
          "url": "compose-jvm-2.2607.5-sources.jar",
          "size": 2064,
          "sha512": "5976e3fe85f250f87c14dcc99d65703cc16f64939bf405db1439868b9dcd5ab7f2092d9c18640b0aad213d72c6bec967bc6841571ce5e2dcaabc2a1f4f34ff0f",
          "sha256": "3197e913c80916c32cc92001150ba3040b65d35ba2291fd0947cbb699182937d",
          "sha1": "a51a6fae1636410b893914bcc9c69a04137511a1",
          "md5": "255d61dc45a6e0ecc0577cfaeaa26433"
        }
      ]
    }
  ]
}
