{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose/2.4/compose-2.4.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "compose",
    "version": "2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "compose-js.klib",
          "url": "compose-js-2.4.klib",
          "size": 14815,
          "sha512": "4293d0ae2801e4e67d4fb1d77f397af9f729a9927eebda186eaf638aca7aebd88e39094e567a0a541973651a81021a796f2ba4eb40afec175498b624619a26d6",
          "sha256": "3d1b77bf684de560677784da2d7e5569b3a441d55d3e11717d16ea2ec88c12ee",
          "sha1": "ff32268a0b6e0132d0beafecea53c399498ac176",
          "md5": "7595614f68270ffc040b9b732b8eedff"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "dev.oom-wg.purejoy.fyl.fytxt",
          "module": "core",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-js.klib",
          "url": "compose-js-2.4.klib",
          "size": 14815,
          "sha512": "4293d0ae2801e4e67d4fb1d77f397af9f729a9927eebda186eaf638aca7aebd88e39094e567a0a541973651a81021a796f2ba4eb40afec175498b624619a26d6",
          "sha256": "3d1b77bf684de560677784da2d7e5569b3a441d55d3e11717d16ea2ec88c12ee",
          "sha1": "ff32268a0b6e0132d0beafecea53c399498ac176",
          "md5": "7595614f68270ffc040b9b732b8eedff"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "compose-js-sources.jar",
          "url": "compose-js-2.4-sources.jar",
          "size": 2081,
          "sha512": "9191c7925e0a1d53463d967ba95f30d14991e7f79bbd98ede0c4eea5034e1e548f716b6adfdcd529da198426e83ede18cc033332cb148e98d57b90cf862ad87c",
          "sha256": "ba5af3f43c6fb224f620897f2baf34bb5447089aca96390fef3b1437212458f2",
          "sha1": "764e6f2bb2db932756f8280d70274ec3c0f39c7a",
          "md5": "6d26b0d41de4b1ee78ed94568718b29c"
        }
      ]
    }
  ]
}
