{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.2607.6/core-2.2607.6.module",
    "group": "ren.shiror.fyl.fytxt",
    "module": "core",
    "version": "2.2607.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-mingwX64Main.klib",
          "url": "core-mingwx64-2.2607.6.klib",
          "size": 15710,
          "sha512": "ba58c6f3e679454a1b47a9bc8203fd006ddd56edbcdc21848d2d2cd4ba33aeb395b758a920ebb65a83b1fbec33589b46042870fb47fc415906e1bf0e1bce799e",
          "sha256": "876eb9064d28c45e6c94b1f11129e91eee34a61db329b333866e7bd5fad67fe9",
          "sha1": "88bb473ca74a965958f3ea3ca4669678ed55c0d3",
          "md5": "15049484a4b44526c9cb4ff81e520804"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-mingwx64-sources.jar",
          "url": "core-mingwx64-2.2607.6-sources.jar",
          "size": 2202,
          "sha512": "8d6bbcd5db3642b2baaeba47b3e1a245c6b0ed862a46ead73cda22773d0180fdf18ca1c9839ff97664906324f8f5d7d7811ee978d309d1c0155fac96cc630fe8",
          "sha256": "45c42503aa3bceb65a8962c959170d406be7be61ad29a22af0796fb1a94214b4",
          "sha1": "3e0eda4c2722e8c9b67865fccf0c9d2c02e3c37c",
          "md5": "e91cf1f5e5d8c81d37e5b6421f87c527"
        }
      ]
    }
  ]
}
