{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.4/core-2.4.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "core",
    "version": "2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosArm32Main.klib",
          "url": "core-watchosarm32-2.4.klib",
          "size": 14421,
          "sha512": "b6ef741496823eda5fed35346cbb9dfda1536e0d65367180050d222fb672f70b8501ab13cf6b188482ce34250d39f75efa8bd2fede31b7fd180837ce4d872d08",
          "sha256": "3dbda9db7f1236d4979e629bfd3959ad2ec9de720ee8af7e4a6008b21239f531",
          "sha1": "ae6b79aea8adba240fff734ab25e123e218fac5d",
          "md5": "c7d39a60a1159abc28d20cdbbde6755b"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-watchosarm32-sources.jar",
          "url": "core-watchosarm32-2.4-sources.jar",
          "size": 2067,
          "sha512": "09424c3eb8f603b9ff26d243fc9f07d9ca4dde587efbf7b97955b4fddf1dd151fb270deac41ace5612aa5acec05a4a51d82191312a52d7782bf9ae733617f71f",
          "sha256": "6b8e77652ae89cdeb0443395804bf449c9d1d8a6336695ac7370e1589dfe827d",
          "sha1": "615b0cf0911375825826bc0bc34c88fb3baab401",
          "md5": "8b7531dbe787e932f77e2d18ea67b235"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosarm32-metadata.jar",
          "url": "core-watchosarm32-2.4-metadata.jar",
          "size": 2448,
          "sha512": "5a744cc6a36762b0a6d38ac83343977751b41f5dba1a7fff77a75d7a3f0e6c764573cc8baa8b26381f43e0488faf441ac23ac51f4aca80a5c8dd563fa9034614",
          "sha256": "8afc00c2852001fe465a7002fb28ccc2f84b01cdc3cfb8be14cbe5ecad074813",
          "sha1": "73c3961d9b0ccca42e02d9d3f1ae7adc59b632ec",
          "md5": "677850743532a5a64f5e3e05424168f5"
        }
      ]
    }
  ]
}
