{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.3/core-2.3.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "core",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-androidNativeX64Main.klib",
          "url": "core-androidnativex64-2.3.klib",
          "size": 16165,
          "sha512": "227634c0349db96621a8002f8d13aaefe966054d41f59eaeb3c25b978197b783aec01bf86e5965ea5106107913161a263aad7ad002de9013e11eca0983c8b728",
          "sha256": "dc51a3c60dc00823e5d86685355207c901a531dc5549570d2aaa619478ba3c1c",
          "sha1": "ad3a0fb347b721dc47736d646876ff3ee747ca1b",
          "md5": "ba46f0ca24aaa4c6170897c867185959"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-androidnativex64-sources.jar",
          "url": "core-androidnativex64-2.3-sources.jar",
          "size": 2251,
          "sha512": "f4752cfe465e8e7982ec4af62adba6e52fca1ed6cd98da1b0cc633e5d4bf27b924d56d8183e232b9c3f303c3a09fa7352ef9aead21bd3398f8044d2fa245d3c2",
          "sha256": "8ff9803118708a0ca82d026723c7b95f6dc36208a72a2f0fb448963e2fdeaa0e",
          "sha1": "9f1baef1d454cdb23058486ed9d56dc616ce26eb",
          "md5": "effbf9037cf2eb7a989aaea962fe1c30"
        }
      ]
    }
  ]
}
