{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose/2.3/compose-2.3.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "compose",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "dev.oom-wg.purejoy.fyl.fytxt",
          "module": "core",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-iosSimulatorArm64Main.klib",
          "url": "compose-iossimulatorarm64-2.3.klib",
          "size": 15011,
          "sha512": "05d9e89a5ef6e8f86238b6f506925602ed930e312c906fd6929a8750c648ec6e37d2324d67a0484f8fb40ebffbf97093d41bdf93df89fb044400a9780195276c",
          "sha256": "3aafbee11da51696a117d0c3dd8b942ffbdd7600c4c1d907994b831e5f8dbd1f",
          "sha1": "10958b6e686ad8d8df318f4ec97b5aa866c29af7",
          "md5": "3f9ac6b22148967977ae1fdaf6a79b4d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-iossimulatorarm64-sources.jar",
          "url": "compose-iossimulatorarm64-2.3-sources.jar",
          "size": 2099,
          "sha512": "7a6be1f73bcff433b6148107a04550863e5712f64c3fb0ccb1c7fd2242e861c9cf12b15831876473af5232d430f3ec0de1e20da088e83a0d4ee2e9e85fb7ea14",
          "sha256": "4253506e010e137ac7809d7abac5a746293e429309e23529375639da9d410e99",
          "sha1": "a4450061f0c11b559f902b1aaa814097cf7f1bb6",
          "md5": "c3ae5762a4e2b3e608541a2b96ef2825"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "dev.oom-wg.purejoy.fyl.fytxt",
          "module": "core",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-iossimulatorarm64-metadata.jar",
          "url": "compose-iossimulatorarm64-2.3-metadata.jar",
          "size": 3243,
          "sha512": "e8bf2f1513a3dbb4c267cabe363e6ef24859e0e8eebdafc375d4fae9c7136e34d40242707d9ab47350d056188e73a08d99ededf43f063d378cb044bfb987b621",
          "sha256": "c8ff2682053a48a62ea246ad269361b22c7f7644ea4ac0f864e1aa796f59246d",
          "sha1": "954aab679e55bfe5aedf8af9f9361d7d3f7e465f",
          "md5": "c36ccf108f361b22e5fd7a588d18ab81"
        }
      ]
    }
  ]
}
