{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose/2.3/compose-2.3.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "compose",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "compose-js.klib",
          "url": "compose-js-2.3.klib",
          "size": 14817,
          "sha512": "3440b55443de5f30eae53f87b6766b51e31366676113a5fd9522da0523913317db12a5903b7d9f2646b235e354b279718edf116c95285d290a0903eb18da940b",
          "sha256": "54c2eaa6795721fc20014f1ddc884a74cee5af0b5a1025c6cb48d08991343131",
          "sha1": "287178e25676bc88a47c8dae1eeceed85a77d18e",
          "md5": "0ebfca17fae5da35dc348da1c7c75999"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "dev.oom-wg.purejoy.fyl.fytxt",
          "module": "core",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-js.klib",
          "url": "compose-js-2.3.klib",
          "size": 14817,
          "sha512": "3440b55443de5f30eae53f87b6766b51e31366676113a5fd9522da0523913317db12a5903b7d9f2646b235e354b279718edf116c95285d290a0903eb18da940b",
          "sha256": "54c2eaa6795721fc20014f1ddc884a74cee5af0b5a1025c6cb48d08991343131",
          "sha1": "287178e25676bc88a47c8dae1eeceed85a77d18e",
          "md5": "0ebfca17fae5da35dc348da1c7c75999"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "compose-js-sources.jar",
          "url": "compose-js-2.3-sources.jar",
          "size": 2081,
          "sha512": "9191c7925e0a1d53463d967ba95f30d14991e7f79bbd98ede0c4eea5034e1e548f716b6adfdcd529da198426e83ede18cc033332cb148e98d57b90cf862ad87c",
          "sha256": "ba5af3f43c6fb224f620897f2baf34bb5447089aca96390fef3b1437212458f2",
          "sha1": "764e6f2bb2db932756f8280d70274ec3c0f39c7a",
          "md5": "6d26b0d41de4b1ee78ed94568718b29c"
        }
      ]
    }
  ]
}
