{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.3/core-2.3.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "core",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-androidNativeArm64Main.klib",
          "url": "core-androidnativearm64-2.3.klib",
          "size": 16178,
          "sha512": "3f396b478dde90fd0e1a927f20d3c032acbb189309f54d3ae13198f07632ecb6d749ce6e37802035089e672d5beb72b0a9397b43b610c85351b15df4a2473e9a",
          "sha256": "f0fb2a932f7ff01ac6397ccbf369eea219a554711c2efc5a53e893ce35e80c96",
          "sha1": "7c0663bff06345b9e8bcfb9ae9a5f9d3edbcb5a7",
          "md5": "d9186f74b0f49ff67de46052552b5e33"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-androidnativearm64-sources.jar",
          "url": "core-androidnativearm64-2.3-sources.jar",
          "size": 2251,
          "sha512": "f4752cfe465e8e7982ec4af62adba6e52fca1ed6cd98da1b0cc633e5d4bf27b924d56d8183e232b9c3f303c3a09fa7352ef9aead21bd3398f8044d2fa245d3c2",
          "sha256": "8ff9803118708a0ca82d026723c7b95f6dc36208a72a2f0fb448963e2fdeaa0e",
          "sha1": "9f1baef1d454cdb23058486ed9d56dc616ce26eb",
          "md5": "effbf9037cf2eb7a989aaea962fe1c30"
        }
      ]
    }
  ]
}
