{
  "formatVersion": "1.1",
  "component": {
    "group": "work.niggergo.app",
    "module": "futago",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "futago-1.2.aar",
          "url": "futago-1.2.aar",
          "size": 8024,
          "sha512": "c2a6f051b09a617ce297d2fc23ce493d92ef7bf7d1ed7bf4fc6bddaffaf1812b0825f7c9d0d65c958ddb48681f8403a2aa5a0035cb25e387931988a30f59f031",
          "sha256": "917ccbbdcb4ad8243c2c592e5cc8a4baa801ac128c720f2e87873cb0582b22ad",
          "sha1": "d234143cbd2622eb67a2a31548d4b37c1003ecb9",
          "md5": "acb7c437fc795a9d6d87b27146ceaca8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "futago-1.2.aar",
          "url": "futago-1.2.aar",
          "size": 8024,
          "sha512": "c2a6f051b09a617ce297d2fc23ce493d92ef7bf7d1ed7bf4fc6bddaffaf1812b0825f7c9d0d65c958ddb48681f8403a2aa5a0035cb25e387931988a30f59f031",
          "sha256": "917ccbbdcb4ad8243c2c592e5cc8a4baa801ac128c720f2e87873cb0582b22ad",
          "sha1": "d234143cbd2622eb67a2a31548d4b37c1003ecb9",
          "md5": "acb7c437fc795a9d6d87b27146ceaca8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "futago-1.2-sources.jar",
          "url": "futago-1.2-sources.jar",
          "size": 1827,
          "sha512": "8656b5ff2830b59d97aa2a5bee286e84c465a6108821d88add444d5d46a9704d2c362c24a789839f9bcff6bd367f0bfa0ab77e04b7006e463f5aa2e8c9d21a09",
          "sha256": "4a0d1b378c2a1a37f969a0e6b968f7d8f626219f22412326032461d7e0f95971",
          "sha1": "ed8be66c3900272babcffcf6a4f57d29b02faa40",
          "md5": "6553ed8d46e3c1e92f7ec1bc18bb39b6"
        }
      ]
    }
  ]
}
