{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.2/core-2.2.module",
    "group": "ren.shiror.fvv",
    "module": "core",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-2.2.aar",
          "size": 58330,
          "sha512": "da6df49151e5db93537d833a5b678b6298f2fbc96115363c35fbbf6c59a013e5a33d5070630bee50d80195458d1a379c0da89cb55d6ad436cd63110e4b386816",
          "sha256": "c8337c5c00ee5b701db19cd270b9207c7bd80f331f2835818a570dc6301b16ba",
          "sha1": "779c13a8babb5586c04563422f2daf74a4e801ca",
          "md5": "4c5e3e51d84b131e6dde7f9efb50e916"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-2.2.aar",
          "size": 58330,
          "sha512": "da6df49151e5db93537d833a5b678b6298f2fbc96115363c35fbbf6c59a013e5a33d5070630bee50d80195458d1a379c0da89cb55d6ad436cd63110e4b386816",
          "sha256": "c8337c5c00ee5b701db19cd270b9207c7bd80f331f2835818a570dc6301b16ba",
          "sha1": "779c13a8babb5586c04563422f2daf74a4e801ca",
          "md5": "4c5e3e51d84b131e6dde7f9efb50e916"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-android-sources.jar",
          "url": "core-android-2.2-sources.jar",
          "size": 8998,
          "sha512": "78c400f65207e60273b19a34d9f97415f2499330a94cd8095b547394b56663ee0277855898089426357f04cf865fb6c488d14d077b528e13fb16e701b5e7be3c",
          "sha256": "354afeb1ada2c2beb46e2c3eccb7dc621a7c6b9c983b732926c35684c3098010",
          "sha1": "358ce7f55705227f350153219d502bf692fdb7c8",
          "md5": "5679cb3b79025933f36726c08e27b7be"
        }
      ]
    }
  ]
}
