{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.4/core-2.4.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "core",
    "version": "2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-linuxArm64Main.klib",
          "url": "core-linuxarm64-2.4.klib",
          "size": 15146,
          "sha512": "5fab11d804d70b80f59370305516fdc3823f63c5facad88d3be67af4244980013d3df1d60c4a572e725cc08c05e4305edc9815090bcad86f912d268163a649c2",
          "sha256": "fe939cbc61687bbdfbddf54c0805347581773b27d1ea0bb334f14d7caa296ad3",
          "sha1": "3a5ee3e3f16c720015473ab624c2d6e4d1213b42",
          "md5": "377fa104eff8cd448d9f1d7db5ba1d0d"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-linuxarm64-sources.jar",
          "url": "core-linuxarm64-2.4-sources.jar",
          "size": 2132,
          "sha512": "e53de45820b05fab09cb9570343cd851ec86043e53dd69454daf33536400b98e94a5605199a4a094646add4fa5dbf37ec154d80f2150b61ce1756d82cf93f217",
          "sha256": "dcdbe159473f959d2ca9f4205cc887ef9f4ec8f0bfc8b97f1c87385818236500",
          "sha1": "d2fd23a30199f0d1f44f9f0b2d004f8890a946fd",
          "md5": "31109e22f427a8773734fc1cd2448af3"
        }
      ]
    }
  ]
}
