{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.4/core-2.4.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "core",
    "version": "2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-androidNativeArm32Main.klib",
          "url": "core-androidnativearm32-2.4.klib",
          "size": 16178,
          "sha512": "a415eb181feee2abe51527ac4b8371f0b65c58cc630230bcd2e83a6e461ebb6ed8200b488797392774bddea3f64a59e12521ad9b1eea521ab5a9bcf672f756b7",
          "sha256": "86a5289bfd7f02c265625720d3e106abcbcd3e33b784b6d01fc5131a68b34129",
          "sha1": "3e093af553abc6c085bdadd0d539a6132ba1b341",
          "md5": "a68b1322cb564e8e68772d5d7715bea9"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-androidnativearm32-sources.jar",
          "url": "core-androidnativearm32-2.4-sources.jar",
          "size": 2251,
          "sha512": "f4752cfe465e8e7982ec4af62adba6e52fca1ed6cd98da1b0cc633e5d4bf27b924d56d8183e232b9c3f303c3a09fa7352ef9aead21bd3398f8044d2fa245d3c2",
          "sha256": "8ff9803118708a0ca82d026723c7b95f6dc36208a72a2f0fb448963e2fdeaa0e",
          "sha1": "9f1baef1d454cdb23058486ed9d56dc616ce26eb",
          "md5": "effbf9037cf2eb7a989aaea962fe1c30"
        }
      ]
    }
  ]
}
