{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose/2.4/compose-2.4.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "compose",
    "version": "2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "compose-wasm-js.klib",
          "url": "compose-wasm-js-2.4.klib",
          "size": 14849,
          "sha512": "a4e53cfe186c101711aff5d16abe9282cc68b8c6268a5c146b21519bc1a6a87692333dccfebf7bf5aacd2bca095b4eabe4ba17c1fc78373cebc702b4cb3ef556",
          "sha256": "115a712d4c16453b17df1a1f0938b68a5b6eead5968aa6acc7a0356de000533d",
          "sha1": "e2025ba6bcef32ce08c6f80d52d8b165c7820384",
          "md5": "5cfec4251cbdeff2922f7ef219086180"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "dev.oom-wg.purejoy.fyl.fytxt",
          "module": "core",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-wasm-js.klib",
          "url": "compose-wasm-js-2.4.klib",
          "size": 14849,
          "sha512": "a4e53cfe186c101711aff5d16abe9282cc68b8c6268a5c146b21519bc1a6a87692333dccfebf7bf5aacd2bca095b4eabe4ba17c1fc78373cebc702b4cb3ef556",
          "sha256": "115a712d4c16453b17df1a1f0938b68a5b6eead5968aa6acc7a0356de000533d",
          "sha1": "e2025ba6bcef32ce08c6f80d52d8b165c7820384",
          "md5": "5cfec4251cbdeff2922f7ef219086180"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "compose-wasm-js-sources.jar",
          "url": "compose-wasm-js-2.4-sources.jar",
          "size": 2081,
          "sha512": "9191c7925e0a1d53463d967ba95f30d14991e7f79bbd98ede0c4eea5034e1e548f716b6adfdcd529da198426e83ede18cc033332cb148e98d57b90cf862ad87c",
          "sha256": "ba5af3f43c6fb224f620897f2baf34bb5447089aca96390fef3b1437212458f2",
          "sha1": "764e6f2bb2db932756f8280d70274ec3c0f39c7a",
          "md5": "6d26b0d41de4b1ee78ed94568718b29c"
        }
      ]
    }
  ]
}
