{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.3/core-2.3.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "core",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-linuxX64Main.klib",
          "url": "core-linuxx64-2.3.klib",
          "size": 15134,
          "sha512": "cc4bd39364fdf28cb6c77f99da5ae02ad6f9964f3d29fabe572f68920f90ad8c98267b4ab2273774c73001b8ab0de87efa9354dd4d943c1cc6d10423853c148e",
          "sha256": "d0c1acae7ad9ee2b8351387491c7422a267be5984d291e870d4e59106c5da124",
          "sha1": "b8dcffbab96f7b07381c8b274e9002bfdd753276",
          "md5": "0f3a4001b0499b8d3bb120bd856e3b07"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-linuxx64-sources.jar",
          "url": "core-linuxx64-2.3-sources.jar",
          "size": 2132,
          "sha512": "e53de45820b05fab09cb9570343cd851ec86043e53dd69454daf33536400b98e94a5605199a4a094646add4fa5dbf37ec154d80f2150b61ce1756d82cf93f217",
          "sha256": "dcdbe159473f959d2ca9f4205cc887ef9f4ec8f0bfc8b97f1c87385818236500",
          "sha1": "d2fd23a30199f0d1f44f9f0b2d004f8890a946fd",
          "md5": "31109e22f427a8773734fc1cd2448af3"
        }
      ]
    }
  ]
}
