{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.2607.5/core-2.2607.5.module",
    "group": "ren.shiror.fyl.fytxt",
    "module": "core",
    "version": "2.2607.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-androidNativeArm64Main.klib",
          "url": "core-androidnativearm64-2.2607.5.klib",
          "size": 16496,
          "sha512": "7a8c6b6202e1c6af885d0fbdd371ac33df3de0ac78a4fc3d44fb3690751bf4a07fb57fee1468e6d11484dca0a5dc4e743a5964f5f311387d003e9b1908cb2e46",
          "sha256": "8c9d02696dd99866b4ef11b3ac74bac1436e11bb31d5a62f6fdc2ceab6263992",
          "sha1": "76b4f115441f3bfdf7be6c2400d26bfcf2d32314",
          "md5": "d530849c530c88a25fea1397e7bfe8d5"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-androidnativearm64-sources.jar",
          "url": "core-androidnativearm64-2.2607.5-sources.jar",
          "size": 2247,
          "sha512": "ebc7b9eabe26b45d9510962b6afde905aaaf6a41c204b70bba071bfb0859236ca675417775a4dfb34099cb163ff7d9cad3a0cec12d4d2e2c1f5f51ee9d4d5987",
          "sha256": "4217ae53b83a1c191c9fe054d59ceec897cd992e3ecb6dd59f7b0b9cf61ffca2",
          "sha1": "4d74c2aeeebfa94e289f640a6632fd6176658e27",
          "md5": "5916ddb6cb42ae22b9455b8ee6b94c91"
        }
      ]
    }
  ]
}
