{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.4/core-2.4.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "core",
    "version": "2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-2.4.aar",
          "size": 14222,
          "sha512": "5125932ba918275bf1ce2bfc79d465c7c03bb525450c5c6de1c8e259a9a863b602146fb145a7a7413e2a77bb5992e9958d3d956ae46e10cd8ee1d82662698146",
          "sha256": "c005479d3c7bbc88287f9aaa515a560276d9b02a826fc6af9c198da8024c28a3",
          "sha1": "10f8bfce0225662a80861c8419572946115ed884",
          "md5": "cddfea63d5d0070a6dc26b7f1c5f130e"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core.aar",
          "url": "core-android-2.4.aar",
          "size": 14222,
          "sha512": "5125932ba918275bf1ce2bfc79d465c7c03bb525450c5c6de1c8e259a9a863b602146fb145a7a7413e2a77bb5992e9958d3d956ae46e10cd8ee1d82662698146",
          "sha256": "c005479d3c7bbc88287f9aaa515a560276d9b02a826fc6af9c198da8024c28a3",
          "sha1": "10f8bfce0225662a80861c8419572946115ed884",
          "md5": "cddfea63d5d0070a6dc26b7f1c5f130e"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-android-sources.jar",
          "url": "core-android-2.4-sources.jar",
          "size": 2248,
          "sha512": "769aa1aea34233024c14f404f6b52b245fd719e279870a93e0aa5aa96dbd4b86e60301fb4dcd022e5f1ab300c9850c020ddcdc802d24e55428c2b9f9e3f002e5",
          "sha256": "b7e61591d1b353b920c6c21f5ff172bb70b56c06ca01ddc2628ac68fcd6fb849",
          "sha1": "9189fc8f90dac25d2f4cd6311b991db9cf157678",
          "md5": "764b20516aabf3bfbc7e9b9ef3c9ec67"
        }
      ]
    }
  ]
}
