{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.2607.5/core-2.2607.5.module",
    "group": "ren.shiror.fyl.fytxt",
    "module": "core",
    "version": "2.2607.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-androidNativeX64Main.klib",
          "url": "core-androidnativex64-2.2607.5.klib",
          "size": 16483,
          "sha512": "89c9dd7fff4bdf5de7fc9a3ead147e4c4ce71db748fa28d138dbe39d234eebe2c8167d7d3efbb4839a61586407f54edf334d8760dcaa9e3f9cc0a65a7761257a",
          "sha256": "614dbd738fe73e207b21899617af5a7f1bcce46d6ab03090adcabde8d4c8f66e",
          "sha1": "d311344cb0f9d03fd90d6b7be61c07ae9e29aee4",
          "md5": "ff54398eae4eecb1d57c3397486767cf"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-androidnativex64-sources.jar",
          "url": "core-androidnativex64-2.2607.5-sources.jar",
          "size": 2247,
          "sha512": "ebc7b9eabe26b45d9510962b6afde905aaaf6a41c204b70bba071bfb0859236ca675417775a4dfb34099cb163ff7d9cad3a0cec12d4d2e2c1f5f51ee9d4d5987",
          "sha256": "4217ae53b83a1c191c9fe054d59ceec897cd992e3ecb6dd59f7b0b9cf61ffca2",
          "sha1": "4d74c2aeeebfa94e289f640a6632fd6176658e27",
          "md5": "5916ddb6cb42ae22b9455b8ee6b94c91"
        }
      ]
    }
  ]
}
