{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.2607.5/core-2.2607.5.module",
    "group": "ren.shiror.fyl.fytxt",
    "module": "core",
    "version": "2.2607.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-linuxArm64Main.klib",
          "url": "core-linuxarm64-2.2607.5.klib",
          "size": 15464,
          "sha512": "7e83571b546bdd8bd1ca30e90e7a964624da5c4d29d47b152befeece280c3548107a9f2d48d6ef5e5c3a2252a03c013496eeee765f0f4a1712e3b6577e3c5fff",
          "sha256": "76f25654092dd397f961639597a42a488618d56616f8c978c93cfcfd306d9a52",
          "sha1": "c6b26f9ab3eaa889156f8aabdea0cb6cb367a481",
          "md5": "6ecfbf6680f7df7780f3d9c09b142540"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-linuxarm64-sources.jar",
          "url": "core-linuxarm64-2.2607.5-sources.jar",
          "size": 2126,
          "sha512": "46715b99c1f2442299cd284ffa1256f6d105435cb2615a1dbbb21e22dbea0a15546ae0c8885d2f5ae1f81fd5966ef5c271192bea5d0516cdfd47b5515152bade",
          "sha256": "5605b1187e1972841323981d49601ab9afdb6719b3d6e4ea6b329fa5f8d097ad",
          "sha1": "1930c580fd7a828d97dbb41e79dea118fd62e159",
          "md5": "f85b1b7c08842f91da28132029781a9a"
        }
      ]
    }
  ]
}
