{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.4/core-2.4.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "core",
    "version": "2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-androidNativeX64Main.klib",
          "url": "core-androidnativex64-2.4.klib",
          "size": 16165,
          "sha512": "f275ffe6cf9fc66115b4ca2c1a5dad57efd64c5ee86737c0f020b4f43fd76b6781a7ba7b2772636baee880d9dd449571a0bab13e27af46839a7aa2bedc2bd61e",
          "sha256": "60dcf041afeebd80419d80b201b216a987b57b4b1d5b3bb05c41d7905dbba9b3",
          "sha1": "618de02a52f82193615eec9bc9d46b7e13176935",
          "md5": "a3cbc285670a858f32630261d64677b2"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-androidnativex64-sources.jar",
          "url": "core-androidnativex64-2.4-sources.jar",
          "size": 2251,
          "sha512": "f4752cfe465e8e7982ec4af62adba6e52fca1ed6cd98da1b0cc633e5d4bf27b924d56d8183e232b9c3f303c3a09fa7352ef9aead21bd3398f8044d2fa245d3c2",
          "sha256": "8ff9803118708a0ca82d026723c7b95f6dc36208a72a2f0fb448963e2fdeaa0e",
          "sha1": "9f1baef1d454cdb23058486ed9d56dc616ce26eb",
          "md5": "effbf9037cf2eb7a989aaea962fe1c30"
        }
      ]
    }
  ]
}
