{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.3/core-2.3.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "core",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosArm64Main.klib",
          "url": "core-iosarm64-2.3.klib",
          "size": 14395,
          "sha512": "cda31ad5845a57c89c150b5e5a74adba26ed8634cf2d72bf85b7f92daac625a953b156dd44bf74f2327638b5dd00c04b1f84a6942a44bac6c3579b6d8c2c4ede",
          "sha256": "064f7ff7d8a04575c99f1e8d7fb66ff53938511e593541176c5b50e52651d37d",
          "sha1": "91ab1c373ca34331d0d6dec3cbabc78ae67f094c",
          "md5": "fa021b99266a588941a19c57b6fcbe13"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-iosarm64-sources.jar",
          "url": "core-iosarm64-2.3-sources.jar",
          "size": 2067,
          "sha512": "09424c3eb8f603b9ff26d243fc9f07d9ca4dde587efbf7b97955b4fddf1dd151fb270deac41ace5612aa5acec05a4a51d82191312a52d7782bf9ae733617f71f",
          "sha256": "6b8e77652ae89cdeb0443395804bf449c9d1d8a6336695ac7370e1589dfe827d",
          "sha1": "615b0cf0911375825826bc0bc34c88fb3baab401",
          "md5": "8b7531dbe787e932f77e2d18ea67b235"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-iosarm64-metadata.jar",
          "url": "core-iosarm64-2.3-metadata.jar",
          "size": 2449,
          "sha512": "f6cf10c8c62438e70a2bbbb49fff7fa67ccc211d209d6c903a3fd128a4ca44bba3db6e6e3a93dcbd9de29e299f201c599d317175ecd14aa325fafd92c8f04381",
          "sha256": "cbac23301b832132572098668058f5707a4bc1f2dd33dbc7728a860375d7e567",
          "sha1": "2d2fd717521279580235c10401622ef7516378cc",
          "md5": "37df65440e181caf77403adc800c787d"
        }
      ]
    }
  ]
}
