{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.2607.5/core-2.2607.5.module",
    "group": "ren.shiror.fyl.fytxt",
    "module": "core",
    "version": "2.2607.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-js.klib",
          "url": "core-js-2.2607.5.klib",
          "size": 15666,
          "sha512": "b1981d73d988646c84300ede305b51ce640cddd12e09c4dbbd45a18dae813204fdfda38ac81460da94d3706aa49d09d56cb48fe784652b56a84996fafcf32f64",
          "sha256": "5da2c2d1d3ae9e1a7bc9440faacf3ed65040a843a23760116f5340b56612c2ae",
          "sha1": "bff1c5c0eab1b7c3e5d93be879672b0ae892289f",
          "md5": "3dd980dff90b1558010cbf445f1e47a4"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-js.klib",
          "url": "core-js-2.2607.5.klib",
          "size": 15666,
          "sha512": "b1981d73d988646c84300ede305b51ce640cddd12e09c4dbbd45a18dae813204fdfda38ac81460da94d3706aa49d09d56cb48fe784652b56a84996fafcf32f64",
          "sha256": "5da2c2d1d3ae9e1a7bc9440faacf3ed65040a843a23760116f5340b56612c2ae",
          "sha1": "bff1c5c0eab1b7c3e5d93be879672b0ae892289f",
          "md5": "3dd980dff90b1558010cbf445f1e47a4"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "core-js-sources.jar",
          "url": "core-js-2.2607.5-sources.jar",
          "size": 2192,
          "sha512": "a0148ccd87829cbbbab0b5ab517dce9976fbf384b4a5316e8b80c88ba9a40b20a4af6e353377da72ded766545cb0ea20ca8b6e16ed4a653982f541a6376d46b5",
          "sha256": "b1d4b37d7798f2894a57db562dd63469ef601ee276a58b85af12a7df9008ccb3",
          "sha1": "08be708d99382771297eef341037caafa6c9ce22",
          "md5": "381a5b345ae6a6a1faddea05c5122c64"
        }
      ]
    }
  ]
}
