{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.3/core-2.3.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "core",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-androidNativeX86Main.klib",
          "url": "core-androidnativex86-2.3.klib",
          "size": 16165,
          "sha512": "049fe787076908666394845beae458a95ea094b9c88b05b838ee15fface06ba239f5e5aa55472f2477b82c4d12bc5b17a631c4669c7ad84e768e1551bb8a7a50",
          "sha256": "f13e94b8cb21d31d4119a9c32c5d123f7890a23e4ada7b2d46c527521f482969",
          "sha1": "c4ad40bd0e989dcb817a4395ecb2bf51e1cdce72",
          "md5": "8428707544590c0b05655f0d464a591c"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-androidnativex86-sources.jar",
          "url": "core-androidnativex86-2.3-sources.jar",
          "size": 2251,
          "sha512": "f4752cfe465e8e7982ec4af62adba6e52fca1ed6cd98da1b0cc633e5d4bf27b924d56d8183e232b9c3f303c3a09fa7352ef9aead21bd3398f8044d2fa245d3c2",
          "sha256": "8ff9803118708a0ca82d026723c7b95f6dc36208a72a2f0fb448963e2fdeaa0e",
          "sha1": "9f1baef1d454cdb23058486ed9d56dc616ce26eb",
          "md5": "effbf9037cf2eb7a989aaea962fe1c30"
        }
      ]
    }
  ]
}
