{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2.3/core-2.3.module",
    "group": "dev.oom-wg.purejoy.fyl.fytxt",
    "module": "core",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-3"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosDeviceArm64Main.klib",
          "url": "core-watchosdevicearm64-2.3.klib",
          "size": 14469,
          "sha512": "4e6354601ac364c8d653d86d7530710b6fe2168665cd040190a5c740fa9bb340117a27722ca3bdfc70aa8f331870caeb057aa5987de33356b4fa90720df2d6f5",
          "sha256": "57fe280c74db9c6cbf3d0a69c3d988bf95482ea2a4a42291c79973782d8a6f75",
          "sha1": "89e442ebcded440f6581b5a418bd31c312f622e7",
          "md5": "a665281f269a76ef3ecb59b5db559406"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "core-watchosdevicearm64-sources.jar",
          "url": "core-watchosdevicearm64-2.3-sources.jar",
          "size": 2067,
          "sha512": "09424c3eb8f603b9ff26d243fc9f07d9ca4dde587efbf7b97955b4fddf1dd151fb270deac41ace5612aa5acec05a4a51d82191312a52d7782bf9ae733617f71f",
          "sha256": "6b8e77652ae89cdeb0443395804bf449c9d1d8a6336695ac7370e1589dfe827d",
          "sha1": "615b0cf0911375825826bc0bc34c88fb3baab401",
          "md5": "8b7531dbe787e932f77e2d18ea67b235"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-watchosdevicearm64-metadata.jar",
          "url": "core-watchosdevicearm64-2.3-metadata.jar",
          "size": 2449,
          "sha512": "f6cf10c8c62438e70a2bbbb49fff7fa67ccc211d209d6c903a3fd128a4ca44bba3db6e6e3a93dcbd9de29e299f201c599d317175ecd14aa325fafd92c8f04381",
          "sha256": "cbac23301b832132572098668058f5707a4bc1f2dd33dbc7728a860375d7e567",
          "sha1": "2d2fd717521279580235c10401622ef7516378cc",
          "md5": "37df65440e181caf77403adc800c787d"
        }
      ]
    }
  ]
}
